name: sofcotest
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  bcrypt: ^1.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.4.0
  get: ^4.7.3
  get_storage: ^2.1.1
  go_router: ^17.1.0
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - .env
   - assets/
   - assets/images/
